### PR TITLE
Add thumbfast integration

### PR DESCRIPTION
**Pull request by po5**
cf. #1

I've kept support for Thumbnailer.lua, it's automatically disabled when thumbfast is detected.  
Users with [thumbfast.lua](https://github.com/po5/thumbfast) should notice better performance.

### CODE REVIEW

**Comment by 1-minute-to-midnight** [comment]
slight issue:
image

**Comment by po5** [comment]
Is it always offset like that, or does it happens when moving the mouse fast? Can't reproduce.

**Comment by 1-minute-to-midnight** [comment]
always

**Comment by 1-minute-to-midnight** [comment]
could you try downloading the script directly and testing it?

**Comment by 1-minute-to-midnight** [comment]
I merged your request, downloaded the script and ran it exactly as is

**Comment by po5** [comment]
Yeah, I tested this before submitting and it does work (with default settings).  
Can you try it with default settings (nothing in script-opts)? And if that is the cause, please send your conf file.

**Comment by 1-minute-to-midnight** [comment]
there is nothing in scripts-opts

**Comment by po5** [comment]
> slight issue: image

This is an issue with MPV-EASY. https://github.com/po5/thumbfast/issues/81

**Pull request merged**
